markdown_extensions:
  - admonition
  - pymdownx.details

site_name: SIE – IFPR Paranavaí
site_description: Documentação institucional da Seção de Inovação e Empreendedorismo – Campus Paranavaí
site_author: Seção de Inovação e Empreendedorismo – Campus Paranavaí

theme:
  name: material
  language: pt-BR

nav:
  - Apresentação SIE: apresentacao.md
  - Diretrizes Operacionais: diretrizes.md

  - Eventos:
      - Visão Geral: eventos.md
      - IFTECH:
          - Apresentação Geral: eventos/iftech/index.md
          - Identidade Visual: eventos/iftech/identidade.md
          - Projetos e participantes: eventos/iftech/projetos.md
          - Infraestrutura e Layout: eventos/iftech/layout.md
          - Avaliação e avaliadores: eventos/iftech/avaliacao.md
          - Relatório e consolidação: eventos/iftech/relatorio.md
  - Documentos:
      - Visão Geral: documentos.md
      - 2025: docs2025.md
      - 2026: docs2026.md

  - Acervo: historico.md
  - Contatos: contatos.md

