site_name: SIE/NIT – IFPR Paranavaí
site_description: Documentação institucional da Seção de Inovação e Empreendedorismo – Campus Paranavaí
site_author: Seção de Inovação e Empreendedorismo – IFPR Paranavaí

theme:
  name: material
  language: pt-BR

nav:
  - Apresentação SIE: apresentacao.md
  - Diretrizes Operacionais: diretrizes.md
  - Eventos: eventos.md
  - Documentos: documentos.md
  - Arquivo Histórico: historico.md
  - Contatos: contatos.md

