site_name: SIE – IFPR Paranavaí
site_description: Documentação institucional da Seção de Inovação e Empreendedorismo – Campus Paranavaí
site_author: Seção de Inovação e Empreendedorismo – Campus Paranavaí

theme:
  name: material
  language: pt-BR

nav:
  - Apresentação SIE: apresentacao.md
  - Diretrizes Operacionais: diretrizes.md
  - Eventos: 
      - Visão Geral: eventos.md
        - IFTECH:
          - Apresentação Geral: eventos/iftech/index.md
          - Identidade do Evento: eventos/iftech/identidade.md
          - Avaliação: eventos/iftech/avaliacao.md
          - Layout e Distribuição: eventos/iftech/layout.md
          - Projetos: eventos/iftech/projetos.md
          - Credenciamento: eventos/iftech/credenciamento.md

  - Documentos:
      - Visão Geral: documentos.md
      - 2025: docs2025.md
      - 2026: docs2026.md
  - Acervo: historico.md
  - Contatos: contatos.md
