site_name: SIE – IFPR Paranavaí
site_description: Documentação institucional da Seção de Inovação e Empreendedorismo – Campus Paranavaí
site_author: Seção de Inovação e Empreendedorismo – IFPR Paranavaí

theme:
  name: material
  language: pt-BR

nav:
  - Apresentação SIE:

  - Diretrizes Operacionais:
      - Atribuições e Competências:
      - Fluxos Internos: 
      - Rotinas Recorrentes: 
      - Ferramentas Utilizadas: 
      - Transição de Gestão: 

  - Eventos:
      - IFTECH:
          - Visão Geral: 
          - Modelo Organizacional: 
          - Edições por Ano:
              - 2024:
              - 2025: 
      - SEPIN:
      - SNEPT: 

  - Documentos:
      - Normativas Permanentes: 
      - Modelos Oficiais: 


  - Arquivo Histórico:
      - Eventos: 
      - Projetos Estratégicos:
      - Registros Institucionais:

  - Contatos:
      - Canais Oficiais: contatos.md
